version: "3"
services:
  app:
    container_name: outoftale-app
    working_dir: /app
    build:
      context: ./app
      target: dev
    volumes:
      - ./app/src:/app/src
      - ./app/.svelte-kit/:/app/.svelte-kit
    ports:
      - 3000:3000

  pb:
    container_name: outoftale-pb
    working_dir: /pb
    build:
      context: ./pb
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
    ports:
      - 8080:8080